import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {bundle} from '@remotion/bundler';import {getCompositions,renderMedia} from '@remotion/renderer';import {loadEpisode,resolveEpisode} from '../src/engine/load';import {compileTimeline,writeTimeline} from '../src/engine/timeline';
const [command='validate',raw='episodes/001-ech-ngoi-day-gieng',...flags]=process.argv.slice(2),dir=resolveEpisode(raw),provider=flags[flags.indexOf('--provider')+1]||'edge';
const validate=()=>{const ep=loadEpisode(dir);for(const shot of ep.shots)for(const d of shot.dialogue?[shot.dialogue]:[])if(d.audio&&!fs.existsSync(path.join(dir,d.audio)))console.warn(`Audio pending: ${d.audio}`);console.log(`✓ ${ep.episode.id}: ${ep.shots.length} shots, schema valid`);return ep};
async function voice(){if(provider!=='edge')throw new Error(`Provider "${provider}" is not installed. Implement TTSProvider and select it here.`);const ep=validate();fs.mkdirSync(path.join(dir,'audio'),{recursive:true});for(const shot of ep.shots){const d=shot.dialogue;if(!d)continue;const out=path.join(dir,d.audio||`audio/${d.id}.mp3`);if(fs.existsSync(out)&&!flags.includes('--force')){console.log(`↷ ${d.id} exists`);continue}const r=spawnSync('python3',['-m','edge_tts','--voice','vi-VN-HoaiMyNeural','--text',d.text,'--write-media',out],{stdio:'inherit'});if(r.status)throw new Error(`Edge TTS failed for ${d.id}`)}syncPublic()}
function syncPublic(){const target=path.resolve('public',path.relative(process.cwd(),dir));fs.mkdirSync(target,{recursive:true});fs.cpSync(path.join(dir,'audio'),path.join(target,'audio'),{recursive:true})}
async function timeline(){const t=await compileTimeline(validate(),dir);writeTimeline(t,dir);console.log(`✓ timeline ${t.duration.toFixed(2)}s, ${Object.keys(t.dialogues).length} voices`)}
async function render(){await timeline();syncPublic();const bundled=await bundle({entryPoint:path.resolve('src/index.tsx')});const comps=await getCompositions(bundled,{inputProps:{}}),comp=comps.find(c=>c.id==='Fable')!;const output=path.resolve('output',`${loadEpisode(dir).episode.id}/demo.mp4`);fs.mkdirSync(path.dirname(output),{recursive:true});await renderMedia({composition:comp,serveUrl:bundled,codec:'h264',outputLocation:output,crf:27});console.log(`✓ ${output}`)}
async function preview(){await timeline();syncPublic();spawnSync('npx',['remotion','studio','src/index.tsx'],{stdio:'inherit'})}
async function main(){if(command==='validate')validate();else if(command==='voice')await voice();else if(command==='timeline'||command==='rebuild-timeline')await timeline();else if(command==='render')await render();else if(command==='preview')await preview();else if(command==='episode'){await voice();await render()}else throw new Error(`Unknown command ${command}`)}main().catch(e=>{console.error(e);process.exit(1)});
